services:
  eddi:
    build:
      context: .
      dockerfile: "./src/main/docker/Dockerfile.jvm"
    image: labsai/eddi:local
    container_name: eddi
    ports:
      - "7070:7070"
      - "7443:7443"      
    environment:
      - QUARKUS_PROFILE=${QUARKUS_PROFILE}
      - MONGODB_CONNECTIONSTRING=mongodb://${MONGO_INITDB_ROOT_USERNAME}:${MONGO_INITDB_ROOT_PASSWORD_ENCODED}@mongodb:27017/${MONGO_DB_NAME}?authSource=admin
      - MONGODB_DATABASE=${MONGO_DB_NAME}
      - SQLITE_DB_PATH=/shared/reviews.db
      - SQLITE_PASSWORD=${SQLITE_PASSWORD}
    depends_on:
      - mongodb
      - sqlite-db
    volumes:
      - sqlite_data:/shared
    networks:
      - eddi-network
    restart: unless-stopped

  mongodb:
    image: mongo:4.2
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
      - MONGO_INITDB_DATABASE=${MONGO_DB_NAME}
    volumes:
      - mongodb_data:/data/db
    networks:
      - eddi-network
    restart: unless-stopped
  
  sqlite-db:
    image: alpine:latest
    container_name: sqlite-db
    user: "0:0"
    command: >
      sh -c "
        apk add --no-cache sqlite &&
        mkdir -p /shared &&
        chmod 777 /shared &&
        sqlite3 /shared/reviews.db 'CREATE TABLE IF NOT EXISTS reviews (id INTEGER PRIMARY KEY AUTOINCREMENT, username TEXT, email TEXT, review TEXT);' &&
        chmod 777 /shared/reviews.db &&
        chown -R root:root /shared &&
        chmod -R 777 /shared &&
        tail -f /dev/null
      "
    volumes:
      - sqlite_data:/shared
    networks:
      - eddi-network
    restart: unless-stopped
networks:
  eddi-network:
    driver: bridge

volumes:
  mongodb_data:
  sqlite_data:
