version: '3'
services:
  eddi:
    image: labsai/eddi:latest
    ports:
      - "7070:7070"
      - "7443:7443"
#      - "5005:5005"
    links:
      - mongodb
    depends_on:
      - mongodb
  mongodb:
    image: mongo:4.2
    restart: always
